src/main/java/com/bipa/bizsurvey/global/common/BaseEntity.java

test commit

---

build.gradle
src/main/java/com/bipa/bizsurvey/domain/voteUserAnswer/domain/VoteUserAnswer.java
src/main/java/com/bipa/bizsurvey/global/config/QueryDslConfig.java
src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
src/main/resources/application.yml

* RedisConfig 클래스를 추가하였습니다. 
* Lettuce를 사용하였습니다.
* Qdsl은 매번 매번 JPAQueryFactory 를 만들어서 사용하는 것이 조금 힘들다고 생각하여 Bean 등록 후 Config 클래스를 따로 만들었습니다.
어떤 변경 사항이 있나요?
close #4

[Feat] : Add redis config, Qdsl config

---

src/main/java/com/bipa/bizsurvey/global/error/ErrorCode.java
src/main/java/com/bipa/bizsurvey/global/error/ErrorDto.java
src/main/java/com/bipa/bizsurvey/global/exceptionHandler/ValidationExceptionHandler.java

* ValidationExceptionHandler(RestControllerAdvice)를 추가하여 Dto 성분에 맞지 않게 요청이 들어왔을 경우 어느 성분에서 에러가 터지는지 체크해서 리턴해주는 ExceptionHandler를 생성 
ex)
{
"httpStatus": "BAD_REQUEST",
"message": "VALIDATION_CHECK : username",
"errors": [
"ID는 필수 입력값입니다."
]
"errorNum":"400"
}
* ErrorCode라는 enum 클래스를 제작,  CustomException 허용
* ErrorDro 클래스를 제작, Error를 공통으로 처리하는 Dto 제작
어떤 변경 사항이 있나요?

[Feat] : Add ValidationExceptionHandler, ErrorDto, ErrorCode

---

build.gradle
src/main/java/com/bipa/bizsurvey/global/config/SecurityConfig.java

[Feat] : Add security config

---

build.gradle
src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/CreatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
src/main/java/com/bipa/bizsurvey/domain/user/repository/UserRepository.java
src/test/java/com/bipa/bizsurvey/domain/community/api/PostControllerTest.java
src/test/java/com/bipa/bizsurvey/domain/community/service/PostServiceTest.java

* Post 생성 로직 제작 
* 컨트롤러 
* @AuthenticationPrincipal 추 후 적용
* 서비스 
* 테스트 코드 
* 테스트 통과
어떤 변경 사항이 있나요?

[Feat] : Post Create 서비스 제작

---

src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
src/main/java/com/bipa/bizsurvey/global/common/RedisService.java

* RedisTemplate를 활용한 저장할 때 직렬화하고 데이터를 꺼내올 때 역직렬화 하는 RedisService 클래스 제작 
* save(String key, T data)
* get(String key, Class<T> classType)
* Test
* test 통과
어떤 변경 사항이 있나요?

[Feat] : add RedisService

---

src/main/java/com/bipa/bizsurvey/domain/survey/dto/CreateAnswerRequest.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/CreateQuestionRequest.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/CreateSurveyRequest.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
src/main/resources/application.yml
src/test/java/com/bipa/bizsurvey/domain/survey/api/SurveyControllerTest.java

WorkspaceRepository추가 ->  SurveyService에서 필요 , 설문지 조회 테스트 추가 , CreateSurveyDto 파일명 변경
어떤 변경 사항이 있나요?

[Refactor] : WorkspaceRepository 추가 및 설문지 조회 기능

---

build.gradle
src/main/java/com/bipa/bizsurvey/BizSurveyBackApplication.java
src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/PostResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/PostRepository.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Workspace.java
src/main/java/com/bipa/bizsurvey/global/common/BizScheduler.java
src/test/java/com/bipa/bizsurvey/domain/community/api/PostControllerTest.java

* 페이징 적용해서 post 조회 로직 제작. 
* controller 
* service
* 테스트 통과
어떤 변경 사항이 있나요?

[Feat] : Post 조회 기능 추가

---

src/main/java/com/bipa/bizsurvey/domain/community/api/PostController.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/CreatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/SearchPostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/UpdatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/postException/PostExceptionHandler.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/postException/PostExceptionType.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/PostRepository.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
src/main/java/com/bipa/bizsurvey/domain/user/exception/UserExceptionType.java
src/main/java/com/bipa/bizsurvey/global/common/BaseEntity.java
src/main/java/com/bipa/bizsurvey/global/exceptionHandler/ValidationExceptionHandler.java
src/main/resources/application.yml
src/test/java/com/bipa/bizsurvey/domain/community/api/PostControllerTest.java
src/test/java/com/bipa/bizsurvey/domain/community/service/PostServiceTest.java

[Feat] : post service 수정 삭제 검색 제작

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityChildCommentController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/ChildComment.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Comment.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/childComment/CreateChildCommentRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/childComment/UpdateChildCommentRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/childComment/ChildCommentResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/childCommentException/ChildCommentException.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/childCommentException/ChildCommentExceptionHandler.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/childCommentException/ChildCommentExceptionType.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/ChildCommentRepository.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/PostRepository.java
src/main/java/com/bipa/bizsurvey/domain/community/service/ChildCommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/service/CommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
src/main/java/com/bipa/bizsurvey/domain/user/api/ClaimController.java
src/main/java/com/bipa/bizsurvey/domain/user/application/ClaimService.java
src/main/java/com/bipa/bizsurvey/domain/user/domain/Claim.java
src/main/java/com/bipa/bizsurvey/domain/user/dto/claim/ClaimListResponse.java
src/main/java/com/bipa/bizsurvey/domain/user/dto/claim/ClaimRequest.java
src/main/java/com/bipa/bizsurvey/domain/user/enums/ClaimReason.java
src/main/java/com/bipa/bizsurvey/domain/user/enums/ClaimType.java
src/main/java/com/bipa/bizsurvey/domain/user/repository/ClaimRepository.java
src/main/java/com/bipa/bizsurvey/global/common/sorting/OrderByNull.java
src/main/java/com/bipa/bizsurvey/global/common/sorting/SortingRequest.java
src/main/java/com/bipa/bizsurvey/global/common/sorting/SortingService.java
src/main/java/com/bipa/bizsurvey/global/common/sorting/SortingStandard.java
src/main/resources/application.yml

어떤 변경 사항이 있나요?
* ChildComment Service 제작
* Claim Service 제작
* 신고된 게시물은 조회, 검색 기능에서 아예 뜨지 않게 제작
* 신고된 댓글은 "신고된 댓글입니다" 로 치환

[Feat] : ChildCommentService 추가

---

src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyController.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
src/main/java/com/bipa/bizsurvey/domain/survey/mapper/SurveyMapper.java

mapper 제거 및 컨트롤러 중복 해결
어떤 변경 사항이 있나요?

[Refactor] : 설문 CRUD 수정

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/PostImages.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/CreatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/UpdatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostImageResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/PostImagesRepository.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostImageService.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java

[Feat] : add postImage service

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/UpdatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/UpdateSurveyPostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/CreateVoteAnswerRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/CreateVoteRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/vote/CreateVoteUserAnswerRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/AnswerPercentageResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteAnswerResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/surveyPostException/SurveyPostException.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/surveyPostException/SurveyPostExceptionHandler.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/surveyPostException/SurveyPostExceptionType.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/PostImagesRepository.java
src/main/java/com/bipa/bizsurvey/domain/community/service/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/service/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/domain/community/service/VoteService.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
src/main/java/com/bipa/bizsurvey/domain/user/domain/User.java

[Feat] : Add SurveyPost Service

---

src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/enums/AccessType.java
src/main/java/com/bipa/bizsurvey/domain/community/service/SurveyPostService.java

[Feat] : Add score service

---

src/main/java/com/bipa/bizsurvey/domain/admin/api/AdminController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/CommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/CreatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostTableResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/enums/CreateType.java
src/main/java/com/bipa/bizsurvey/global/log/LoggingAspect.java

* best 게시물 선정 로직 제작
* best 항목을 미리 뽑아 놓은 다음
* 포함하고 있는지 아닌지 판단해서 해당하는 경우가 있는 경우 'best' 문자열 추가해 리턴
어떤 변경 사항이 있나요?

[Feat] : add best tag

---

src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/ChildCommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/CommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/comment/CommentResponse.java

* 댓글과 대댓글 함께 리턴
어떤 변경 사항이 있나요?

[Refactor] : ChildCommentService

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostTitleResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/postException/PostExceptionType.java
src/main/java/com/bipa/bizsurvey/global/common/CommonScheduler.java
src/main/java/com/bipa/bizsurvey/global/common/RedisService.java

* 검색어 자동 완성 리턴 컨트롤러 로직 수정
어떤 변경 사항이 있나요?

[Refactor] : refactor findPostTitle()

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/global/common/CommonScheduler.java

* bestPostId를 뽑아내는 로직 -> redis 캐싱으로 변경
* bset를 리턴해주는 로직 수정
어떤 변경 사항이 있나요?

[Refactor] : refactor post service

---

src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyController.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/UserSurveyResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/request/ParticipateSurvey.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/AnswerResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/ChartAndTextResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/FileResultResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/QuestionResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/ScoreAnswerCount.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/ScoreResultResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/SurveyResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/enums/AnswerType.java
src/main/java/com/bipa/bizsurvey/domain/survey/enums/Correct.java
src/main/java/com/bipa/bizsurvey/domain/survey/enums/SurveyType.java
src/main/java/com/bipa/bizsurvey/domain/survey/mapper/SurveyMapper.java
src/test/java/com/bipa/bizsurvey/domain/survey/application/statistics/StatisticsServiceImpTest.java

[Refactor] : 설문지 CRUD 리팩토링

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/ContactController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/SseEmitters.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Contact.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/WorkspaceAdmin.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/ContactDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyRepository.java
src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java

- 리사이징 이미지 파일 임시경로 리턴하는 오류 수정
- workspace CRUD 프론트 연동하면서 변경된 내용 반영
어떤 변경 사항이 있나요?

[Refactor] : S3 Storage & workspace CRUD 리팩토링

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/SurveyListResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/UserScoreResponse.java

설문 리스트 조회 기능에 설문지 타입 추가
어떤 변경 사항이 있나요?

[Refactor] : 설문 리스트 dto 타입 추가

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/SurveyListInCommunityResponse.java
src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java

설문 작성 리스트 dto에 워크스페이스 소유주 추가
어떤 변경 사항이 있나요?

[Refactor] : 설문 리스트 dto수정

---

src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java

[Refactor] : 설문 리스트 목록 조회 정렬 추가

---

src/main/java/com/bipa/bizsurvey/domain/admin/api/AdminController.java
src/main/java/com/bipa/bizsurvey/domain/admin/application/AdminClaimService.java
src/main/java/com/bipa/bizsurvey/domain/admin/application/AdminUserService.java
src/main/java/com/bipa/bizsurvey/domain/admin/dto/claim/ClaimListResponse.java
src/main/java/com/bipa/bizsurvey/domain/admin/dto/user/AdminUserResponse.java
src/main/java/com/bipa/bizsurvey/domain/admin/dto/user/AdminUserSignupCountResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/repository/PostRepository.java
src/main/java/com/bipa/bizsurvey/domain/user/application/EmailSendService.java
src/main/java/com/bipa/bizsurvey/domain/user/enums/Plan.java
src/main/java/com/bipa/bizsurvey/domain/user/repository/ClaimRepository.java
src/main/java/com/bipa/bizsurvey/domain/user/repository/UserRepository.java
src/main/java/com/bipa/bizsurvey/global/config/SecurityConfig.java
src/main/java/com/bipa/bizsurvey/global/config/jwt/AdminJwtAuthenticationFilter.java

[Feat] : admin 컨트롤러 수정
어떤 변경 사항이 있나요?

[Feat] : admin 컨트롤러 수정

---

src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyCommunityController.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java
src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedListDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
src/main/resources/application.yml
src/test/java/com/bipa/bizsurvey/domain/workspace/application/ContactServiceTests.java

- 관리자 및 공유 설문 로직 수정 및 추가
어떤 변경 사항이 있나요?

[Feat] : 관리자 및 공유 설문 로직 수정 및 추가

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
src/main/java/com/bipa/bizsurvey/domain/survey/repository/UserSurveyResponseRepository.java

설문 커뮤니티 참가 인원수 조회 메소드 추가
어떤 변경 사항이 있나요?

[Feat] : surveyPost 참가수 조회 메소드

---

src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/global/common/storage/Domain.java

* surveyPostService 리팩토링
어떤 변경 사항이 있나요?

[Refactor] : refactor surveyPostService

---

src/main/java/com/bipa/bizsurvey/domain/survey/repository/QuestionRepository.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedList.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurveyResponse.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyResponseDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyResponseRepository.java

설문지 외부 공유 및 기본형 설문지 참가 및 통계 구현
어떤 변경 사항이 있나요?

[Feat] : 설문지 외부 공유 및 기본형 설문지 참가 및 통계 구현

---

build.gradle
src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyController.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/Question.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java
src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
src/main/java/com/bipa/bizsurvey/infra/s3/AwsS3Service.java
src/main/java/com/bipa/bizsurvey/infra/s3/FileUtil.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3Controller.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3Domain.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3Folder.java
src/main/java/com/bipa/bizsurvey/infra/s3/ShareType.java
src/main/java/com/bipa/bizsurvey/infra/s3/UploadSurveyFileDto.java
src/test/java/com/bipa/bizsurvey/domain/community/service/PostServiceTest.java
src/test/java/com/bipa/bizsurvey/domain/survey/application/statistics/StatisticsServiceImpTest.java

엑셀 기능 추가 및 설문지 리스트 수정
어떤 변경 사항이 있나요?

[Feat] : 엑셀 기능 추가

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyResponseDto.java
src/test/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyServiceTest.java

외부공유 설문지 통계기능 구현
Resolves : #114
어떤 변경 사항이 있나요?

[Feat] : 외부공유 설문지 통계기능 구현

---

src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/Post.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java
src/main/java/com/bipa/bizsurvey/domain/user/application/ClaimService.java
src/main/java/com/bipa/bizsurvey/domain/user/domain/Claim.java

* 설문 상세 페이지 리턴하는 부분 설정
어떤 변경 사항이 있나요?

[Refactor] : refactor SurveyPostResponse.java

---

src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/UpdateSurveyPostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java

[Refactor] : 설문 게시글 수정 dto변경

---

src/main/java/com/bipa/bizsurvey/domain/community/api/SurveyCommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/PostImageService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/UpdatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostResponse.java

[Refactor] : refactor search service

---

src/main/java/com/bipa/bizsurvey/domain/admin/api/AdminController.java
src/main/java/com/bipa/bizsurvey/domain/admin/application/AdminCommunityService.java
src/main/java/com/bipa/bizsurvey/domain/user/application/UserService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
src/main/java/com/bipa/bizsurvey/global/config/jwt/JwtAuthenticationFilter.java
src/main/java/com/bipa/bizsurvey/global/config/jwt/JwtVO.java

[Feat] : userService 수정
어떤 변경 사항이 있나요?

[Feat] : userService 수정

---

src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
src/main/resources/application.yml
src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminServiceTests.java

- 배포 프로필 backend 도메인 변경
어떤 변경 사항이 있나요?

[Refactor] : 배포 프로필 backend 도메인 변경

---

build.gradle

[Chore] : build 커맨드 추가

---

build.gradle

Reverts BIPA-8-3/BIZSurvey_BACK#129

Revert "[Chore] : build 커맨드 추가"

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteExceptionType.java

[Refactor] : refactor vote service

---

src/main/resources/application.yml

- prod profile 수정
어떤 변경 사항이 있나요?

[Chore] : prod profile 수정

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityVoteController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/VoteService.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/vote/VoteResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/exception/voteException/VoteExceptionType.java
src/main/resources/application.yml

- prod profile 수정
어떤 변경 사항이 있나요?

prod profile 수정

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityChildCommentController.java
src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityCommentController.java

[Feat] : test

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java

[Refactor] : 엑셀 파일 이름 변경

---

src/main/java/com/bipa/bizsurvey/domain/user/dto/PasswordUpdateRequest.java

[Feat] : PasswordUpdateRequest 수정
어떤 변경 사항이 있나요?

[Feat] : PasswordUpdateRequest 수정

---

src/main/resources/application.yml

[Chore] : 배포 프로파일 변경

---

src/main/java/com/bipa/bizsurvey/global/common/email/MailUtil.java

[Refactor] : 메일 이미지 수정

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/ChildCommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/CommentService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/childComment/ChildCommentResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/comment/CommentResponse.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/post/PostResponse.java

* 게시물 상세 페이지에서 유저 디테일 이미지 추가 
어떤 변경 사항이 있나요?

[Refactor] : refactor post detail

---

src/main/java/com/bipa/bizsurvey/domain/user/application/EmailSendService.java

[Feat] : front 주소 수정
어떤 변경 사항이 있나요?

[Feat] : front 주소 수정

---

src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java

- Update S3StorageServiceImpl
- 깨진 코드 수정
어떤 변경 사항이 있나요?

[Refactor] : Update S3StorageServiceImpl

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
src/main/java/com/bipa/bizsurvey/global/config/RedisConfig.java
src/main/resources/application.yml

- redis 비밀번호 추가 & 워크스페이스 접근 권한 수정
어떤 변경 사항이 있나요?

[Feat] : redis 비밀번호 추가 & 워크스페이스 접근 권한 수정

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceRepository.java
src/main/java/com/bipa/bizsurvey/global/common/storage/DeleteFileRequest.java
src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java
src/test/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceServiceTests.java

S3 여러파일 삭제 컨트롤러 추가 && workspace 권한 추가
Resolves : #160, #161
어떤 변경 사항이 있나요?

[Feat] : S3 여러파일 삭제 컨트롤러 추가 && workspace 권한 추가

---

src/main/java/com/bipa/bizsurvey/global/common/storage/StorageController.java
src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
src/main/java/com/bipa/bizsurvey/global/common/storage/TemporaryFileConfirmRequest.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java

- S3 임시저장 파일 확정 메소드 추가
어떤 변경 사항이 있나요?

[Feat] : S3 임시저장 파일 확정 메소드 추가

---

src/main/java/com/bipa/bizsurvey/domain/community/api/CommunityPostController.java
src/main/java/com/bipa/bizsurvey/domain/community/application/SurveyPostService.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/post/CreatePostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/CreateSurveyPostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/request/surveyPost/UpdateSurveyPostRequest.java
src/main/java/com/bipa/bizsurvey/domain/community/dto/response/surveyPost/SurveyPostCardResponse.java

[Feat] : refactor SurveyPost service

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/Answer.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/UserSurveyResponse.java
src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
src/main/java/com/bipa/bizsurvey/infra/s3/S3StorageServiceImpl.java

[Refactor] : 설문 파일 수정

---

src/main/java/com/bipa/bizsurvey/domain/community/application/PostImageService.java
src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java

[Refactor] : 버그 수정

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceService.java

[Refactor] : 워크스페이스 권한 수정 

---

src/main/java/com/bipa/bizsurvey/domain/survey/api/SurveyController.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java

api 수정 nickname -> userId
어떤 변경 사항이 있나요?

[Refactor] : 개별응답 변경

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/SharedSurveyDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/SharedSurveyRepository.java
src/main/resources/application.yml

- 서버 파일 업로드 용량 설정
- 워크스페이스 외부공유 마감기한 수정기능 추가
- Resolves : #172, #173
어떤 변경 사항이 있나요?

[Feat] : 마감기한 추가 & 파일 업로드 용량 설정

---

src/main/java/com/bipa/bizsurvey/domain/survey/domain/Answer.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/Question.java
src/main/java/com/bipa/bizsurvey/domain/survey/domain/Survey.java

answer컬럼 및 설문 컬럼 조건 수정
어떤 변경 사항이 있나요?

[Refactor] : 설문 question, answer column수정

---

src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Contact.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/SharedSurvey.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/Workspace.java

- 워크스페이스 entity 수정
어떤 변경 사항이 있나요?

[Refactor] : 워크스페이스 entity 수정

---

src/main/java/com/bipa/bizsurvey/domain/community/application/PostService.java
src/main/java/com/bipa/bizsurvey/domain/community/domain/SurveyPost.java
src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyCommunityService.java

[Refactor] refactor domain

---

src/main/java/com/bipa/bizsurvey/domain/user/api/OAuth2Controller.java
src/main/java/com/bipa/bizsurvey/domain/user/exception/UserExceptionType.java

[Feat] : 카카오 로그인 신고 로직 추가
어떤 변경 사항이 있나요?

[Feat] : 카카오 로그인 신고 로직 추가

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/SurveyService.java
src/main/java/com/bipa/bizsurvey/domain/survey/repository/SurveyRepository.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/api/WorkspaceAdminController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/ContactService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/WorkspaceAdminService.java
src/main/java/com/bipa/bizsurvey/domain/workspace/domain/WorkspaceAdmin.java
src/main/java/com/bipa/bizsurvey/domain/workspace/dto/WorkspaceAdminDto.java
src/main/java/com/bipa/bizsurvey/domain/workspace/repository/WorkspaceAdminRepository.java
src/main/java/com/bipa/bizsurvey/global/common/RedisService.java
src/main/java/com/bipa/bizsurvey/global/common/storage/StorageService.java
src/main/resources/application.yml

[Refacor] : 통합 배포

---

src/main/java/com/bipa/bizsurvey/domain/survey/application/StatisticsService.java
src/main/java/com/bipa/bizsurvey/domain/survey/dto/response/ScoreResultResponse.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java

[Fix] : 점수 설문 순서 정렬

---

src/main/java/com/bipa/bizsurvey/domain/workspace/api/SharedSurveyController.java
src/main/java/com/bipa/bizsurvey/domain/workspace/application/SharedSurveyService.java

[[Refactor] : 링크 검증 메세지 수정](https://github.com/BIPA-8-3/BIZSurvey_BACK/commit/ec7aab0a26cfb727fc2425c0b45ce1f292b8e5ce)
어떤 변경 사항이 있나요?

[Refactor] : 링크 검증 메세지 수정 
